version: '3.7'

services:
  azure-keyvault-emulator:
    image: basistheory/azure-keyvault-emulator:latest
    ports:
      - 10090:10090
    volumes:
      - $PWD/local-certs:/https
    environment:
      - ASPNETCORE_URLS=https://+:10090
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/azure-key-vault-emulator.pfx
      - KeyVault__Name=azure-keyvault-emulator
