apiName: Vault
hideGenerationTimestamp: true
#interfacePrefix: true
nullableReferenceTypes: false
#optionalAssemblyInfo: true
packageName: BasisTheory.net
#returnICollection: true
#sourceFolder: /src
targetFramework: netstandard2.0;netstandard2.1
#useCollection: true