/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationTemplateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationTemplate
        //private ApplicationTemplate instance;

        public ApplicationTemplateTests()
        {
            // TODO uncomment below to create an instance of ApplicationTemplate
            //instance = new ApplicationTemplate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationTemplate
        /// </summary>
        [Fact]
        public void ApplicationTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationTemplate
            //Assert.IsType<ApplicationTemplate>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ApplicationType'
        /// </summary>
        [Fact]
        public void ApplicationTypeTest()
        {
            // TODO unit test for the property 'ApplicationType'
        }
        /// <summary>
        /// Test the property 'TemplateType'
        /// </summary>
        [Fact]
        public void TemplateTypeTest()
        {
            // TODO unit test for the property 'TemplateType'
        }
        /// <summary>
        /// Test the property 'IsStarter'
        /// </summary>
        [Fact]
        public void IsStarterTest()
        {
            // TODO unit test for the property 'IsStarter'
        }
        /// <summary>
        /// Test the property 'Rules'
        /// </summary>
        [Fact]
        public void RulesTest()
        {
            // TODO unit test for the property 'Rules'
        }
        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Fact]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }

    }

}
