/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test
{
    /// <summary>
    ///  Class for testing AuthenticateThreeDSSessionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthenticateThreeDSSessionRequestTests
    {
        // TODO uncomment below to declare an instance variable for AuthenticateThreeDSSessionRequest
        //private AuthenticateThreeDSSessionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AuthenticateThreeDSSessionRequest
            //instance = new AuthenticateThreeDSSessionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AuthenticateThreeDSSessionRequest
        /// </summary>
        [Test]
        public void AuthenticateThreeDSSessionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AuthenticateThreeDSSessionRequest
            //Assert.IsInstanceOf(typeof(AuthenticateThreeDSSessionRequest), instance);
        }


        /// <summary>
        /// Test the property 'AuthenticationCategory'
        /// </summary>
        [Test]
        public void AuthenticationCategoryTest()
        {
            // TODO unit test for the property 'AuthenticationCategory'
        }
        /// <summary>
        /// Test the property 'AuthenticationType'
        /// </summary>
        [Test]
        public void AuthenticationTypeTest()
        {
            // TODO unit test for the property 'AuthenticationType'
        }
        /// <summary>
        /// Test the property 'ChallengePreference'
        /// </summary>
        [Test]
        public void ChallengePreferenceTest()
        {
            // TODO unit test for the property 'ChallengePreference'
        }
        /// <summary>
        /// Test the property 'PurchaseInfo'
        /// </summary>
        [Test]
        public void PurchaseInfoTest()
        {
            // TODO unit test for the property 'PurchaseInfo'
        }
        /// <summary>
        /// Test the property 'MerchantInfo'
        /// </summary>
        [Test]
        public void MerchantInfoTest()
        {
            // TODO unit test for the property 'MerchantInfo'
        }
        /// <summary>
        /// Test the property 'RequestorInfo'
        /// </summary>
        [Test]
        public void RequestorInfoTest()
        {
            // TODO unit test for the property 'RequestorInfo'
        }
        /// <summary>
        /// Test the property 'CardholderInfo'
        /// </summary>
        [Test]
        public void CardholderInfoTest()
        {
            // TODO unit test for the property 'CardholderInfo'
        }
        /// <summary>
        /// Test the property 'BroadcastInfo'
        /// </summary>
        [Test]
        public void BroadcastInfoTest()
        {
            // TODO unit test for the property 'BroadcastInfo'
        }
        /// <summary>
        /// Test the property 'MessageExtensions'
        /// </summary>
        [Test]
        public void MessageExtensionsTest()
        {
            // TODO unit test for the property 'MessageExtensions'
        }

    }

}
