/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing BankVerificationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BankVerificationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BankVerificationRequest
        //private BankVerificationRequest instance;

        public BankVerificationRequestTests()
        {
            // TODO uncomment below to create an instance of BankVerificationRequest
            //instance = new BankVerificationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BankVerificationRequest
        /// </summary>
        [Fact]
        public void BankVerificationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" BankVerificationRequest
            //Assert.IsType<BankVerificationRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Fact]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Fact]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'RoutingNumber'
        /// </summary>
        [Fact]
        public void RoutingNumberTest()
        {
            // TODO unit test for the property 'RoutingNumber'
        }

    }

}
