/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing CardDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CardDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CardDetails
        //private CardDetails instance;

        public CardDetailsTests()
        {
            // TODO uncomment below to create an instance of CardDetails
            //instance = new CardDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CardDetails
        /// </summary>
        [Fact]
        public void CardDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CardDetails
            //Assert.IsType<CardDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Bin'
        /// </summary>
        [Fact]
        public void BinTest()
        {
            // TODO unit test for the property 'Bin'
        }
        /// <summary>
        /// Test the property 'Last4'
        /// </summary>
        [Fact]
        public void Last4Test()
        {
            // TODO unit test for the property 'Last4'
        }

    }

}
