/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing CreateTokenRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateTokenRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateTokenRequest
        //private CreateTokenRequest instance;

        public CreateTokenRequestTests()
        {
            // TODO uncomment below to create an instance of CreateTokenRequest
            //instance = new CreateTokenRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateTokenRequest
        /// </summary>
        [Fact]
        public void CreateTokenRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateTokenRequest
            //Assert.IsType<CreateTokenRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Privacy'
        /// </summary>
        [Fact]
        public void PrivacyTest()
        {
            // TODO unit test for the property 'Privacy'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'SearchIndexes'
        /// </summary>
        [Fact]
        public void SearchIndexesTest()
        {
            // TODO unit test for the property 'SearchIndexes'
        }
        /// <summary>
        /// Test the property 'FingerprintExpression'
        /// </summary>
        [Fact]
        public void FingerprintExpressionTest()
        {
            // TODO unit test for the property 'FingerprintExpression'
        }
        /// <summary>
        /// Test the property 'Mask'
        /// </summary>
        [Fact]
        public void MaskTest()
        {
            // TODO unit test for the property 'Mask'
        }
        /// <summary>
        /// Test the property 'DeduplicateToken'
        /// </summary>
        [Fact]
        public void DeduplicateTokenTest()
        {
            // TODO unit test for the property 'DeduplicateToken'
        }
        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }
        /// <summary>
        /// Test the property 'Containers'
        /// </summary>
        [Fact]
        public void ContainersTest()
        {
            // TODO unit test for the property 'Containers'
        }

    }

}
