/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing CreateTenantConnectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateTenantConnectionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateTenantConnectionRequest
        //private CreateTenantConnectionRequest instance;

        public CreateTenantConnectionRequestTests()
        {
            // TODO uncomment below to create an instance of CreateTenantConnectionRequest
            //instance = new CreateTenantConnectionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateTenantConnectionRequest
        /// </summary>
        [Fact]
        public void CreateTenantConnectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateTenantConnectionRequest
            //Assert.IsType<CreateTenantConnectionRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Strategy'
        /// </summary>
        [Fact]
        public void StrategyTest()
        {
            // TODO unit test for the property 'Strategy'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }

    }

}
