/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test
{
    /// <summary>
    ///  Class for testing GetPermissions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPermissionsTests
    {
        // TODO uncomment below to declare an instance variable for GetPermissions
        //private GetPermissions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetPermissions
            //instance = new GetPermissions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetPermissions
        /// </summary>
        [Test]
        public void GetPermissionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetPermissions
            //Assert.IsInstanceOf(typeof(GetPermissions), instance);
        }


        /// <summary>
        /// Test the property 'ApplicationType'
        /// </summary>
        [Test]
        public void ApplicationTypeTest()
        {
            // TODO unit test for the property 'ApplicationType'
        }

    }

}
