/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing PatchProxyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatchProxyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PatchProxyRequest
        //private PatchProxyRequest instance;

        public PatchProxyRequestTests()
        {
            // TODO uncomment below to create an instance of PatchProxyRequest
            //instance = new PatchProxyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PatchProxyRequest
        /// </summary>
        [Fact]
        public void PatchProxyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PatchProxyRequest
            //Assert.IsType<PatchProxyRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DestinationUrl'
        /// </summary>
        [Fact]
        public void DestinationUrlTest()
        {
            // TODO unit test for the property 'DestinationUrl'
        }
        /// <summary>
        /// Test the property 'RequestTransform'
        /// </summary>
        [Fact]
        public void RequestTransformTest()
        {
            // TODO unit test for the property 'RequestTransform'
        }
        /// <summary>
        /// Test the property 'ResponseTransform'
        /// </summary>
        [Fact]
        public void ResponseTransformTest()
        {
            // TODO unit test for the property 'ResponseTransform'
        }
        /// <summary>
        /// Test the property 'Application'
        /// </summary>
        [Fact]
        public void ApplicationTest()
        {
            // TODO unit test for the property 'Application'
        }
        /// <summary>
        /// Test the property '_Configuration'
        /// </summary>
        [Fact]
        public void _ConfigurationTest()
        {
            // TODO unit test for the property '_Configuration'
        }
        /// <summary>
        /// Test the property 'RequireAuth'
        /// </summary>
        [Fact]
        public void RequireAuthTest()
        {
            // TODO unit test for the property 'RequireAuth'
        }

    }

}
