/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test
{
    /// <summary>
    ///  Class for testing Proxy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProxyTests
    {
        // TODO uncomment below to declare an instance variable for Proxy
        //private Proxy instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Proxy
            //instance = new Proxy();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Proxy
        /// </summary>
        [Test]
        public void ProxyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Proxy
            //Assert.IsInstanceOf(typeof(Proxy), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Test]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DestinationUrl'
        /// </summary>
        [Test]
        public void DestinationUrlTest()
        {
            // TODO unit test for the property 'DestinationUrl'
        }
        /// <summary>
        /// Test the property 'RequestReactorId'
        /// </summary>
        [Test]
        public void RequestReactorIdTest()
        {
            // TODO unit test for the property 'RequestReactorId'
        }
        /// <summary>
        /// Test the property 'ResponseReactorId'
        /// </summary>
        [Test]
        public void ResponseReactorIdTest()
        {
            // TODO unit test for the property 'ResponseReactorId'
        }
        /// <summary>
        /// Test the property 'RequireAuth'
        /// </summary>
        [Test]
        public void RequireAuthTest()
        {
            // TODO unit test for the property 'RequireAuth'
        }
        /// <summary>
        /// Test the property 'RequestTransform'
        /// </summary>
        [Test]
        public void RequestTransformTest()
        {
            // TODO unit test for the property 'RequestTransform'
        }
        /// <summary>
        /// Test the property 'ResponseTransform'
        /// </summary>
        [Test]
        public void ResponseTransformTest()
        {
            // TODO unit test for the property 'ResponseTransform'
        }
        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Test]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property '_Configuration'
        /// </summary>
        [Test]
        public void _ConfigurationTest()
        {
            // TODO unit test for the property '_Configuration'
        }
        /// <summary>
        /// Test the property 'ProxyHost'
        /// </summary>
        [Test]
        public void ProxyHostTest()
        {
            // TODO unit test for the property 'ProxyHost'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'ModifiedBy'
        /// </summary>
        [Test]
        public void ModifiedByTest()
        {
            // TODO unit test for the property 'ModifiedBy'
        }
        /// <summary>
        /// Test the property 'ModifiedAt'
        /// </summary>
        [Test]
        public void ModifiedAtTest()
        {
            // TODO unit test for the property 'ModifiedAt'
        }

    }

}
