/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing ReactorFormulaConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReactorFormulaConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReactorFormulaConfiguration
        //private ReactorFormulaConfiguration instance;

        public ReactorFormulaConfigurationTests()
        {
            // TODO uncomment below to create an instance of ReactorFormulaConfiguration
            //instance = new ReactorFormulaConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReactorFormulaConfiguration
        /// </summary>
        [Fact]
        public void ReactorFormulaConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReactorFormulaConfiguration
            //Assert.IsType<ReactorFormulaConfiguration>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
