/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing ThreeDSMerchantRiskInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ThreeDSMerchantRiskInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ThreeDSMerchantRiskInfo
        //private ThreeDSMerchantRiskInfo instance;

        public ThreeDSMerchantRiskInfoTests()
        {
            // TODO uncomment below to create an instance of ThreeDSMerchantRiskInfo
            //instance = new ThreeDSMerchantRiskInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ThreeDSMerchantRiskInfo
        /// </summary>
        [Fact]
        public void ThreeDSMerchantRiskInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ThreeDSMerchantRiskInfo
            //Assert.IsType<ThreeDSMerchantRiskInfo>(instance);
        }


        /// <summary>
        /// Test the property 'DeliveryEmail'
        /// </summary>
        [Fact]
        public void DeliveryEmailTest()
        {
            // TODO unit test for the property 'DeliveryEmail'
        }
        /// <summary>
        /// Test the property 'DeliveryTimeFrame'
        /// </summary>
        [Fact]
        public void DeliveryTimeFrameTest()
        {
            // TODO unit test for the property 'DeliveryTimeFrame'
        }
        /// <summary>
        /// Test the property 'GiftCardAmount'
        /// </summary>
        [Fact]
        public void GiftCardAmountTest()
        {
            // TODO unit test for the property 'GiftCardAmount'
        }
        /// <summary>
        /// Test the property 'GiftCardCount'
        /// </summary>
        [Fact]
        public void GiftCardCountTest()
        {
            // TODO unit test for the property 'GiftCardCount'
        }
        /// <summary>
        /// Test the property 'GiftCardCurrency'
        /// </summary>
        [Fact]
        public void GiftCardCurrencyTest()
        {
            // TODO unit test for the property 'GiftCardCurrency'
        }
        /// <summary>
        /// Test the property 'PreOrderPurchase'
        /// </summary>
        [Fact]
        public void PreOrderPurchaseTest()
        {
            // TODO unit test for the property 'PreOrderPurchase'
        }
        /// <summary>
        /// Test the property 'PreOrderDate'
        /// </summary>
        [Fact]
        public void PreOrderDateTest()
        {
            // TODO unit test for the property 'PreOrderDate'
        }
        /// <summary>
        /// Test the property 'ReorderedPurchase'
        /// </summary>
        [Fact]
        public void ReorderedPurchaseTest()
        {
            // TODO unit test for the property 'ReorderedPurchase'
        }
        /// <summary>
        /// Test the property 'ShippingMethod'
        /// </summary>
        [Fact]
        public void ShippingMethodTest()
        {
            // TODO unit test for the property 'ShippingMethod'
        }

    }

}
