/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing ThreeDSPurchaseInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ThreeDSPurchaseInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ThreeDSPurchaseInfo
        //private ThreeDSPurchaseInfo instance;

        public ThreeDSPurchaseInfoTests()
        {
            // TODO uncomment below to create an instance of ThreeDSPurchaseInfo
            //instance = new ThreeDSPurchaseInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ThreeDSPurchaseInfo
        /// </summary>
        [Fact]
        public void ThreeDSPurchaseInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ThreeDSPurchaseInfo
            //Assert.IsType<ThreeDSPurchaseInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Exponent'
        /// </summary>
        [Fact]
        public void ExponentTest()
        {
            // TODO unit test for the property 'Exponent'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'TransactionType'
        /// </summary>
        [Fact]
        public void TransactionTypeTest()
        {
            // TODO unit test for the property 'TransactionType'
        }
        /// <summary>
        /// Test the property 'InstallmentCount'
        /// </summary>
        [Fact]
        public void InstallmentCountTest()
        {
            // TODO unit test for the property 'InstallmentCount'
        }
        /// <summary>
        /// Test the property 'RecurringExpiration'
        /// </summary>
        [Fact]
        public void RecurringExpirationTest()
        {
            // TODO unit test for the property 'RecurringExpiration'
        }
        /// <summary>
        /// Test the property 'RecurringFrequency'
        /// </summary>
        [Fact]
        public void RecurringFrequencyTest()
        {
            // TODO unit test for the property 'RecurringFrequency'
        }

    }

}
