/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing ThreeDSMobileSdkRenderOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ThreeDSMobileSdkRenderOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ThreeDSMobileSdkRenderOptions
        //private ThreeDSMobileSdkRenderOptions instance;

        public ThreeDSMobileSdkRenderOptionsTests()
        {
            // TODO uncomment below to create an instance of ThreeDSMobileSdkRenderOptions
            //instance = new ThreeDSMobileSdkRenderOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ThreeDSMobileSdkRenderOptions
        /// </summary>
        [Fact]
        public void ThreeDSMobileSdkRenderOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ThreeDSMobileSdkRenderOptions
            //Assert.IsType<ThreeDSMobileSdkRenderOptions>(instance);
        }


        /// <summary>
        /// Test the property 'SdkInterface'
        /// </summary>
        [Fact]
        public void SdkInterfaceTest()
        {
            // TODO unit test for the property 'SdkInterface'
        }
        /// <summary>
        /// Test the property 'SdkUiType'
        /// </summary>
        [Fact]
        public void SdkUiTypeTest()
        {
            // TODO unit test for the property 'SdkUiType'
        }

    }

}
