/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing TokenReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenReportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenReport
        //private TokenReport instance;

        public TokenReportTests()
        {
            // TODO uncomment below to create an instance of TokenReport
            //instance = new TokenReport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenReport
        /// </summary>
        [Fact]
        public void TokenReportInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenReport
            //Assert.IsType<TokenReport>(instance);
        }


        /// <summary>
        /// Test the property 'IncludedMonthlyActiveTokens'
        /// </summary>
        [Fact]
        public void IncludedMonthlyActiveTokensTest()
        {
            // TODO unit test for the property 'IncludedMonthlyActiveTokens'
        }
        /// <summary>
        /// Test the property 'MonthlyActiveTokens'
        /// </summary>
        [Fact]
        public void MonthlyActiveTokensTest()
        {
            // TODO unit test for the property 'MonthlyActiveTokens'
        }
        /// <summary>
        /// Test the property 'MetricsByType'
        /// </summary>
        [Fact]
        public void MetricsByTypeTest()
        {
            // TODO unit test for the property 'MetricsByType'
        }
        /// <summary>
        /// Test the property 'TotalTokens'
        /// </summary>
        [Fact]
        public void TotalTokensTest()
        {
            // TODO unit test for the property 'TotalTokens'
        }

    }

}
