/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BasisTheory.net.Api;
using BasisTheory.net.Model;
using BasisTheory.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BasisTheory.net.Test.Model
{
    /// <summary>
    ///  Class for testing TokenMetrics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenMetricsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenMetrics
        //private TokenMetrics instance;

        public TokenMetricsTests()
        {
            // TODO uncomment below to create an instance of TokenMetrics
            //instance = new TokenMetrics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenMetrics
        /// </summary>
        [Fact]
        public void TokenMetricsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenMetrics
            //Assert.IsType<TokenMetrics>(instance);
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'LastCreatedAt'
        /// </summary>
        [Fact]
        public void LastCreatedAtTest()
        {
            // TODO unit test for the property 'LastCreatedAt'
        }

    }

}
