/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using BasisTheory.net.Client;
using BasisTheory.net.Api;
// uncomment below to import models
//using BasisTheory.net.Model;

namespace BasisTheory.net.Test.Api
{
    /// <summary>
    ///  Class for testing ReactorsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ReactorsApiTests : IDisposable
    {
        private ReactorsApi instance;

        public ReactorsApiTests()
        {
            instance = new ReactorsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReactorsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ReactorsApi
            //Assert.IsType<ReactorsApi>(instance);
        }

        /// <summary>
        /// Test Create
        /// </summary>
        [Fact]
        public void CreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateReactorRequest createReactorRequest = null;
            //var response = instance.Create(createReactorRequest);
            //Assert.IsType<Reactor>(response);
        }

        /// <summary>
        /// Test Delete
        /// </summary>
        [Fact]
        public void DeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //instance.Delete(id);
        }

        /// <summary>
        /// Test Get
        /// </summary>
        [Fact]
        public void GetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<Guid> id = null;
            //string name = null;
            //int? page = null;
            //string start = null;
            //int? size = null;
            //var response = instance.Get(id, name, page, start, size);
            //Assert.IsType<ReactorPaginatedList>(response);
        }

        /// <summary>
        /// Test GetById
        /// </summary>
        [Fact]
        public void GetByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetById(id);
            //Assert.IsType<Reactor>(response);
        }

        /// <summary>
        /// Test Patch
        /// </summary>
        [Fact]
        public void PatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //PatchReactorRequest patchReactorRequest = null;
            //instance.Patch(id, patchReactorRequest);
        }

        /// <summary>
        /// Test React
        /// </summary>
        [Fact]
        public void ReactTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //ReactRequest reactRequest = null;
            //var response = instance.React(id, reactRequest);
            //Assert.IsType<ReactResponse>(response);
        }

        /// <summary>
        /// Test Update
        /// </summary>
        [Fact]
        public void UpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //UpdateReactorRequest updateReactorRequest = null;
            //var response = instance.Update(id, updateReactorRequest);
            //Assert.IsType<Reactor>(response);
        }
    }
}
