/*
 * Basis Theory API
 *
 * ## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BasisTheory.net.Client.OpenAPIDateConverter;

namespace BasisTheory.net.Model
{
    /// <summary>
    /// ThreeDSMobileSdkRenderOptions
    /// </summary>
    [DataContract(Name = "ThreeDSMobileSdkRenderOptions")]
    public partial class ThreeDSMobileSdkRenderOptions : IEquatable<ThreeDSMobileSdkRenderOptions>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDSMobileSdkRenderOptions" /> class.
        /// </summary>
        /// <param name="sdkInterface">sdkInterface.</param>
        /// <param name="sdkUiType">sdkUiType.</param>
        public ThreeDSMobileSdkRenderOptions(string sdkInterface = default(string), List<string> sdkUiType = default(List<string>))
        {
            this.SdkInterface = sdkInterface;
            this.SdkUiType = sdkUiType;
        }

        /// <summary>
        /// Gets or Sets SdkInterface
        /// </summary>
        [DataMember(Name = "sdk_interface", EmitDefaultValue = true)]
        public string SdkInterface { get; set; }

        /// <summary>
        /// Gets or Sets SdkUiType
        /// </summary>
        [DataMember(Name = "sdk_ui_type", EmitDefaultValue = true)]
        public List<string> SdkUiType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ThreeDSMobileSdkRenderOptions {\n");
            sb.Append("  SdkInterface: ").Append(SdkInterface).Append("\n");
            sb.Append("  SdkUiType: ").Append(SdkUiType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ThreeDSMobileSdkRenderOptions);
        }

        /// <summary>
        /// Returns true if ThreeDSMobileSdkRenderOptions instances are equal
        /// </summary>
        /// <param name="input">Instance of ThreeDSMobileSdkRenderOptions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ThreeDSMobileSdkRenderOptions input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SdkInterface == input.SdkInterface ||
                    (this.SdkInterface != null &&
                    this.SdkInterface.Equals(input.SdkInterface))
                ) && 
                (
                    this.SdkUiType == input.SdkUiType ||
                    this.SdkUiType != null &&
                    input.SdkUiType != null &&
                    this.SdkUiType.SequenceEqual(input.SdkUiType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SdkInterface != null)
                {
                    hashCode = (hashCode * 59) + this.SdkInterface.GetHashCode();
                }
                if (this.SdkUiType != null)
                {
                    hashCode = (hashCode * 59) + this.SdkUiType.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
