name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    environment: PR

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: bash scripts/build.sh

  pr-security-check:
    name: PR Security Check
    uses: Basis-Theory/public-security-workflows/.github/workflows/pr-check.yml@master
    secrets: inherit