name: Release

on:
  push:
    branches: [master]

jobs:
  build-publish:
    environment: PROD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_SEMANTIC_RELEASE_PAT }}

      - name: Start Deploy Message
        uses: Basis-Theory/github-actions/deploy-slack-action@master
        with:
          slack-api-token: ${{ secrets.SLACK_DUCKBOT_API_KEY }}
          channel: ${{ vars.SLACK_DUCKBOT_RELEASE_CHANNEL_ID }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"

      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_PAT }}
          NUGET_API_KEY: ${{ secrets.NUGET_PUBLISHING_TOKEN }}

      - name: Stop Deploy Message
        if: always()
        uses: Basis-Theory/github-actions/deploy-slack-action@master
        with:
          slack-api-token: ${{ secrets.SLACK_DUCKBOT_API_KEY }}
          channel: ${{ vars.SLACK_DUCKBOT_RELEASE_CHANNEL_ID }}
          status: "done"
